#pragma once

// Deprecated source-compatibility umbrella. Production code must include the
// focused owner of each contract instead of importing this facade.
#include "Animation Cache.h"
#include "Civ Quotes.h"
#include "Disease.h"
#include "GameSettings.h"
#include "Grid Direction.h"
#include "Item Types.h"
#include "Overhead Types.h"
#include "Soldier Background Types.h"
#include "Soldier Class.h"
#include "Soldier Palette.h"
#include "Soldier Patrol Types.h"
#include "Soldier Profile Constants.h"
#include "Soldier Profile.h"
#include "Soldier Stat Types.h"
#include "Strategic Path Types.h"
#include "Taunt Types.h"
#include "TacticalActor.h"
#include "TacticalActorAiBehavior.h"
#include "TacticalActorAnimationSelection.h"
#include "TacticalActorAnimationState.h"
#include "TacticalActorBattleSounds.h"
#include "TacticalActorBleeding.h"
#include "TacticalActorBloodState.h"
#include "TacticalActorConditions.h"
#include "TacticalActorConsumables.h"
#include "TacticalActorCrowBehavior.h"
#include "TacticalActorDamageFeedback.h"
#include "TacticalActorDamageResolution.h"
#include "TacticalActorDebug.h"
#include "TacticalActorEmploymentTypes.h"
#include "TacticalActorEquipment.h"
#include "TacticalActorEvents.h"
#include "TacticalActorInteractions.h"
#include "TacticalActorInterrupts.h"
#include "TacticalActorLifecycle.h"
#include "TacticalActorLighting.h"
#include "TacticalActorLocomotion.h"
#include "TacticalActorLongActions.h"
#include "TacticalActorModifiers.h"
#include "TacticalActorMovementAudio.h"
#include "TacticalActorMovementState.h"
#include "TacticalActorPendingActionTypes.h"
#include "TacticalActorPredicates.h"
#include "TacticalActorQuoteFlags.h"
#include "TacticalActorSkills.h"
#include "TacticalActorStateFlags.h"
#include "TacticalActorWorldPlacement.h"
#include "TacticalDestinationTypes.h"
#include "Timer Control.h"
#include "vobject.h"
#include "worlddef.h"

#include <iterator>
#include <vector>
