#pragma once

#include "types.h"

#include <cstdint>

class TacticalActor;

enum
{
	SKILLS_FIRST = 0,
	SKILLS_RADIO_FIRST = SKILLS_FIRST,
	SKILLS_RADIO_ARTILLERY = SKILLS_RADIO_FIRST,
	SKILLS_RADIO_JAM,
	SKILLS_RADIO_SCAN_FOR_JAM,
	SKILLS_RADIO_LISTEN,
	SKILLS_RADIO_CALLREINFORCEMENTS,
	SKILLS_RADIO_TURNOFF,
	SKILLS_RADIO_ACTIVATE_TURNCOATS_ALL,
	SKILLS_RADIO_LAST = SKILLS_RADIO_ACTIVATE_TURNCOATS_ALL,
	SKILLS_INTEL_FIRST,
	SKILLS_INTEL_CONCEAL = SKILLS_INTEL_FIRST,
	SKILLS_INTEL_GATHERINTEL,
	SKILLS_CREATE_TURNCOAT,
	SKILLS_ACTIVATE_TURNCOATS,
	SKILLS_ACTIVATE_TURNCOATS_ALL,
	SKILLS_INTEL_LAST = SKILLS_ACTIVATE_TURNCOATS_ALL,
	SKILLS_DISGUISE_FIRST,
	SKILLS_DISGUISE_APPLY_DISGUISE = SKILLS_DISGUISE_FIRST,
	SKILLS_DISGUISE_REMOVE_DISGUISE,
	SKILLS_DISGUISE_TEST_DISGUISE,
	SKILLS_DISGUISE_REMOVE_CLOTHES,
	SKILLS_DISGUISE_LAST = SKILLS_DISGUISE_REMOVE_CLOTHES,
	SKILLS_VARIOUS_FIRST,
	SKILLS_SPOTTER = SKILLS_VARIOUS_FIRST,
	SKILLS_FOCUS,
	SKILLS_DRAG,
	SKILLS_FILL_CANTEENS,
	SKILLS_VARIOUS_LAST = SKILLS_FILL_CANTEENS,
	SKILLS_MAX,
};

BOOLEAN HAS_SKILL_TRAIT(
	TacticalActor* actor, UINT8 skillTraitNumber);
INT8 NUM_SKILL_TRAITS(
	TacticalActor* actor, UINT8 skillTraitNumber);
UINT8 GetSquadleadersCountInVicinity(
	TacticalActor* actor,
	BOOLEAN withHigherLevel,
	BOOLEAN doNotCheckDistance);

namespace TacticalActorSkills
{
	[[nodiscard]] bool canUse(
		TacticalActor& actor,
		std::int32_t skill,
		bool checkForActionPoints = true,
		std::int32_t targetGridNo = -1);
	[[nodiscard]] bool use(
		TacticalActor& actor,
		std::uint32_t skill,
		std::int32_t targetGridNo,
		std::uint32_t targetId);
	[[nodiscard]] const wchar_t* description(
		TacticalActor& actor,
		std::int32_t skill,
		std::int32_t targetGridNo = -1);
}
