#pragma once

// Persistent quote-history bits. The first and extended groups occupy
// separate component fields, so their numeric ranges intentionally overlap.
#define SOLDIER_QUOTE_SAID_IN_SHIT                     0x0001
#define SOLDIER_QUOTE_SAID_LOW_BREATH                  0x0002
#define SOLDIER_QUOTE_SAID_BEING_PUMMELED              0x0004
#define SOLDIER_QUOTE_SAID_NEED_SLEEP                  0x0008
#define SOLDIER_QUOTE_SAID_LOW_MORAL                   0x0010
#define SOLDIER_QUOTE_SAID_MULTIPLE_CREATURES          0x0020
#define SOLDIER_QUOTE_SAID_ANNOYING_MERC               0x0040
#define SOLDIER_QUOTE_SAID_LIKESGUN                    0x0080
#define SOLDIER_QUOTE_SAID_DROWNING                    0x0100
#define SOLDIER_QUOTE_SAID_ROTTINGCORPSE               0x0200
#define SOLDIER_QUOTE_SAID_SPOTTING_CREATURE_ATTACK    0x0400
#define SOLDIER_QUOTE_SAID_SMELLED_CREATURE            0x0800
#define SOLDIER_QUOTE_SAID_ANTICIPATING_DANGER         0x1000
#define SOLDIER_QUOTE_SAID_WORRIED_ABOUT_CREATURES     0x2000
#define SOLDIER_QUOTE_SAID_PERSONALITY                 0x4000
#define SOLDIER_QUOTE_SAID_FOUND_SOMETHING_NICE        0x8000

#define SOLDIER_QUOTE_SAID_EXT_HEARD_SOMETHING         0x0001
#define SOLDIER_QUOTE_SAID_EXT_SEEN_CREATURE_ATTACK    0x0002
#define SOLDIER_QUOTE_SAID_EXT_USED_BATTLESOUND_HIT    0x0004
#define SOLDIER_QUOTE_SAID_EXT_CLOSE_CALL              0x0008
#define SOLDIER_QUOTE_SAID_EXT_MORRIS                  0x0010
#define SOLDIER_QUOTE_SAID_EXT_MIKE                    0x0010
static_assert(
	SOLDIER_QUOTE_SAID_EXT_MORRIS ==
	SOLDIER_QUOTE_SAID_EXT_MIKE);

#define SOLDIER_QUOTE_SAID_DONE_ASSIGNMENT             0x0020
#define SOLDIER_QUOTE_SAID_BUDDY_1_WITNESSED           0x0040
#define SOLDIER_QUOTE_SAID_BUDDY_2_WITNESSED           0x0080
#define SOLDIER_QUOTE_SAID_BUDDY_3_WITNESSED           0x0100
#define SOLDIER_QUOTE_SAID_THOUGHT_KILLED_YOU          0x0200
#define SOLDIER_QUOTE_SAID_BUDDY_4_WITNESSED           0x0400
#define SOLDIER_QUOTE_SAID_BUDDY_5_WITNESSED           0x0800
#define SOLDIER_QUOTE_SAID_BUDDY_6_WITNESSED           0x1000
